"""add_clerk_org_id_to_organisation

Revision ID: 30277d26774a
Revises: 3b5ed08bc4d3
Create Date: 2026-06-30 16:16:06.646346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '30277d26774a'
down_revision: Union[str, None] = '3b5ed08bc4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('clerk_org_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_organisation_clerk_org_id'), 'organisation', ['clerk_org_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organisation_clerk_org_id'), table_name='organisation')
    op.drop_column('organisation', 'clerk_org_id')
    # ### end Alembic commands ###
