"""initial_schema

Revision ID: 3b5ed08bc4d3
Revises: xxxx
Create Date: 2026-06-30 15:00:50.840775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3b5ed08bc4d3'
down_revision: Union[str, None] = 'xxxx'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('PE_FIRM', 'FAMILY_OFFICE', name='orgtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisation_id'), 'organisation', ['id'], unique=False)
    op.create_index(op.f('ix_organisation_name'), 'organisation', ['name'], unique=False)
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_id'), 'funds', ['id'], unique=False)
    op.create_index(op.f('ix_funds_name'), 'funds', ['name'], unique=False)
    op.create_index(op.f('ix_funds_org_id'), 'funds', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funds_org_id'), table_name='funds')
    op.drop_index(op.f('ix_funds_name'), table_name='funds')
    op.drop_index(op.f('ix_funds_id'), table_name='funds')
    op.drop_table('funds')
    op.drop_index(op.f('ix_organisation_name'), table_name='organisation')
    op.drop_index(op.f('ix_organisation_id'), table_name='organisation')
    op.drop_table('organisation')
    # ### end Alembic commands ###
