"""claim_kind and assertion_class on claims

Revision ID: 7b4b05b6d9c8
Revises: c9aaf2c46b16
Create Date: 2026-07-23 13:05:58.419804

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

revision: str = "7b4b05b6d9c8"
down_revision: str | None = "fb49da6a9bc0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("claims", sa.Column("claim_kind", sa.String(length=12), nullable=True))
    op.add_column("claims", sa.Column("assertion_class", sa.String(length=24), nullable=True))
    # The contract's rules made non-bypassable in the database, matching the
    # CheckConstraints on the model. Autogenerate does not emit these.
    op.create_check_constraint(
        "ck_claims_claim_kind",
        "claims",
        "claim_kind IS NULL OR claim_kind IN ('quantitative', 'qualitative')",
    )
    op.create_check_constraint(
        "ck_claims_assertion_class",
        "claims",
        "assertion_class IS NULL OR assertion_class IN ("
        "'related_party', 'operating_model', 'market_definition', 'competitive_position', "
        "'commercial_terms', 'risk_or_dependency', 'plan_or_commitment')",
    )
    op.create_check_constraint(
        "ck_claims_qualitative_has_class",
        "claims",
        "claim_kind IS DISTINCT FROM 'qualitative' OR assertion_class IS NOT NULL",
    )


def downgrade() -> None:
    op.drop_constraint("ck_claims_qualitative_has_class", "claims", type_="check")
    op.drop_constraint("ck_claims_assertion_class", "claims", type_="check")
    op.drop_constraint("ck_claims_claim_kind", "claims", type_="check")
    op.drop_column("claims", "assertion_class")
    op.drop_column("claims", "claim_kind")
