"""users table, nullable org type, users RLS

Revision ID: c9aaf2c46b16
Revises: 9e796d5efdb7
Create Date: 2026-07-16 10:42:16.406547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c9aaf2c46b16'
down_revision: Union[str, None] = '9e796d5efdb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('login_method', sa.String(length=50), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=64), nullable=False),
    sa.Column('clerk_org_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_org_id'), 'users', ['clerk_org_id'], unique=False)
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.alter_column('organisation', 'type',
               existing_type=postgresql.ENUM('PE_FIRM', 'FAMILY_OFFICE', name='orgtype'),
               nullable=True)
    # ### end Alembic commands ###

    # RLS: users are isolated by their org's Clerk id, same as organisation.
    # FOR ALL derives WITH CHECK from USING, so INSERTs (JIT provisioning in
    # get_db) are only allowed for the request's own org.
    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY org_isolation ON users
            FOR ALL TO dd_app
            USING (clerk_org_id = current_setting('app.org_id', true))
    """)


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS org_isolation ON users")
    op.execute("ALTER TABLE users DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organisation', 'type',
               existing_type=postgresql.ENUM('PE_FIRM', 'FAMILY_OFFICE', name='orgtype'),
               nullable=False)
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_org_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
